Map<String, String> enUS = {
  "category": "Category",
  "categories": "Categories",
  "welcomeallEventsapp": "Welcome To AllEvents App",
  "datetime": "Date&Time",
  "sort": "Sort",
  "personaldata": "Personal Data",
  "help": "Help",
  "aboutapp": "About App",
  "signout": "Sign Out",
  "vanue": "Vanue",
  "viewmap": "View Map",
  "booknow": "Book Now",
  "eventphotos": "Event's Photos",
  "hostAttendance": "Host Reviews By Attendance",
  "sbruniverse": "SBR Universe",
  "follow": "Follow",
  "absolutelyexpect": "Absolutely great time. Way better than expect",
  "suggestionsforyou": "Suggestions For You",
  "allevents": "All Events",
  "explore": "Explore",
  "feed": "Feed",
  "profile": "Profile"
};
